version: '3.3'

services:
  App:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app/:/app
    entrypoint: "tail -f /dev/null"
